[package]
name = "gpu-observer-host-probe-ebpf"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[workspace]

[dependencies]
aya-ebpf = { version = "0.2.1", default-features = false }
gpu-observer-host-probe-common = { path = "../common" }

[[bin]]
name = "gpu-observer-host-probe"
path = "src/main.rs"

[profile.release]
codegen-units = 1
debug = 2
lto = true
opt-level = 3
panic = "abort"
